mail-config:
  username: arthurcorreia.dev@gmail.com
  subject: Contato Portfólio
spring:
  application:
    name: portfolio-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portfolio_db?useTimezone=true&serverTimezone=UTC
    username: developer
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: sendermail.dev@gmail.com
    password: vhmx xrlw gjcq kfbt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
