CREATE TABLE IF NOT EXISTS `PROJECTS` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `NAME` VARCHAR(50) NOT NULL,
    `DESCRIPTION` VARCHAR(255) NOT NULL,
    `IMAGE_URL` VARCHAR(150) NOT NULL,
    `DEPLOY_URL` VARCHAR(150) NOT NULL,
    `REPOSITORY_URL` VARCHAR(150) NOT NULL,
    `ACTIVE` TINYINT(1) NOT NULL
);